import Head from "next/head";

import { ReactElement } from "react";
import ComicList from "../components/comic/comicList";
import Navbar from "../components/navbar";
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Infinte Comics | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div>
        <ComicList />
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Navbar>{page}</Navbar>;
};

export default Home;
