import Head from "next/head";

import { ReactElement } from "react";
import ComicList from "../components/comic/comicList";
import Navbar from "../components/navbar";
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Infinite Comics | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div>
        <div className="mx-auto flex max-w-2xl flex-col py-4 px-4 sm:py-8 sm:px-6 lg:max-w-7xl lg:px-8">
          <h1 className="text-center text-2xl font-bold text-gray-900 md:text-left">
            News Comic
          </h1>
          <ComicList />
        </div>
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Navbar>{page}</Navbar>;
};

export default Home;
