import Head from "next/head";

import { ReactElement } from "react";
import Navbar from "../../components/navbar";
import { NextPageWithLayout } from "../_app";

const Comics: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Infinte Comics | Comics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div></div>
    </>
  );
};

Comics.getLayout = function getLayout(page: ReactElement) {
  return <Navbar>{page}</Navbar>;
};

export default Comics;
