import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { ReactElement } from "react";
import { NextPageWithLayout } from "../_app";
import Navbar from "../../components/navbar";
import Form from "../../components/form";
import ComicForm from "../../components/comic/comicForm";

const Comics: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Infinte Comics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
    </>
  );
};

Comics.getLayout = function getLayout(page: ReactElement) {
  return <Navbar>{page}</Navbar>;
};

export default Comics;
